#!/bin/bash

export customer=$1
export rootPath="${HOME}/git/SS-git/DEV/"
export serverPath="server"
export empServerPath="emp-server"
export empWebPath="emp-web"
customers=("ext15" "ext13")

if [ -z ${customer} ] ; then
    echo "Which customer? Currently supported are:"
    select opt in "${customers[@]}"
    do
        case $opt in
            ${customers[0]})
                customer=${opt};
                break
                ;;
            ${customers[1]})
                customer=${opt};
                break
                ;;
            *)
                echo "Wrong selection. Please choose a number between 1 and ${#customers[@]}";
        esac
    done
fi

tmux new-session -s emp-all 'docker container start -a $(docker ps -af name=postgres -q) ; zsh' \; \
    split-window -v -p 95 'docker container start -a $(docker ps -af name=${customer} -q) ; zsh' \; \
    split-window -v -p 60 'cd ${rootPath}${empServerPath}; ./gradlew clean coreBootRun ; zsh' \; \
    split-window -v -p 60 'cd ${rootPath}web; npm run start:${customer} ; zsh' \; \
    split-window -h 'cd ${rootPath}${empWebPath}; npm run start:all'
